"""Add signed_up_via_google to users

Revision ID: 51f73fa801d0
Revises: b4505a14779a
Create Date: 2025-05-09 14:50:44.656511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51f73fa801d0'
down_revision: Union[str, None] = 'b4505a14779a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('signed_up_via_google', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'signed_up_via_google')
    # ### end Alembic commands ###
