"""your message

Revision ID: b4505a14779a
Revises: 50d6f9c672af
Create Date: 2025-05-09 13:36:25.952351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4505a14779a'
down_revision: Union[str, None] = '50d6f9c672af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_picture', sa.String(), nullable=True))
    op.drop_column('users', 'profile_picture_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_picture_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'profile_picture')
    # ### end Alembic commands ###
